const slownik = {
  'pl': {
    'settings': 'Ustawienia',
    'home': 'Dom',
    'exit': 'Wyjście',
    'tools': 'Narzędzia',
    'chooseLang': 'Wybierz język',
    'hole': 'Tolerancja otworu',
    'walu': 'Tolerancja wału',
    'obr': 'Obroty narzędzia',
    'sred': 'Średnica narzędzia',
    'diam': 'Prędkość skrawania',
    'speed': 'Obroty',
    'jednostka': 'obr/min',
    'btnReset': 'Reset PL',
    'wartosc': 'Wartość',
    'tolerancja': 'Tolerancja',
    'posuwNarzedzia': 'Posuw narzędzia',
    'pobierz': 'Pobierz',
    'iloscOstrzy': 'Ilość ostrzy',
    'posuwNaZab': 'Posuw na ząb',
    'posuw': 'Posuw',
    'symboleTolerancji': 'Symbole tolerancji',
    'zamknij': 'Zamknij',
    'symbol': 'Symbol',

  },
  'en': {
    'settings': 'Settings',
    'home': 'Home',
    'exit': 'Exit',
    'tools': 'Tools',
    'chooseLang': 'Choose Language',
    'hole': 'Hole tolerance',
    'walu': 'Shaft tolerance',
    'obr': 'Tool rotation',
    'sred': 'Tool diameter',
    'diam': 'Cutting speed',
    'speed': 'Rotation',
    'jednostka': 'rpm',
    'btnReset': 'Reset ENG',
    'wartosc': 'Value',
    'tolerancja': 'Tolerance',
    'posuwNarzedzia': 'Tool feed',
    'pobierz': 'Retrieve',
    'iloscOstrzy': 'Number of blades',
    'posuwNaZab': 'Feed per tooth',
    'posuw': 'Feed',
    'symboleTolerancji': 'Tolerance symbols',
    'zamknij': 'Close',
    'symbol': 'Symbol',
  },
};

export default slownik;
